name: msmd

dependencies:
- pip
- python
- numpy
- matplotlib
- scikit-learn
- qt
- pyqt
- cython
- jupyter

- pip:
  - madmom==0.16.1
  - opencv-python==4.0.0.21
  - pyyaml==3.13
  - pdfminer.six==20181108
  - python-ly==0.9.5
  - abjad==3.0.0
  - scikit-image==0.14.2
  - tqdm==4.31.1
  - dtw==1.3.3
  - pretty_midi==0.2.8
